name: anim2
description: A basic 2D html5 animation library. Very basic.
version: 1.0.0
#author: Ben Sheron <benmosheron@gmail.com>
#homepage: https://github.com/benmosheron/

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  generic_vector_tools: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
